XML/XML/Models/HLV_CLB.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace XML.Models
{
    public partial class HLV_CLB
    {

        public string VAITRO { get; set; }
        public string MACLB { get; set; }
        public string MAHLV { get; set; }

    }
}

XML/XML/Controllers/HLV_CLBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using XML.Models;
using XML.QLData;

namespace XML.Controllers
{
    public class HLV_CLBController : Controller
    {
        // GET: HLV_CLB
        public ActionResult Index()
        {

            QLTong<HLV_CLB> qLHLV_CLB = new QLHLV_CLB();
            qLHLV_CLB.getdata();


            return View(qLHLV_CLB.DS);
        }

        // GET: HLV_CLB/Details/5
        public ActionResult Details(string id)
        {
            QLTong<HLV_CLB> t = new QLHLV_CLB();
            if (!t.istimkiem(id))
            {
                return HttpNotFound();
            }

            return View(t.xemChiTiet(id));
        }

        // GET: HLV_CLB/Create
        public ActionResult Create()
        {
            QLTong<HLV_CLB> t = new QLHLV_CLB();
            ViewBag.MACLB = t.getListSelect("CAULACBO", "TENCLB");
            ViewBag.MAHLV = t.getListSelect("HLV", "TENHLV");
            return View();
        }

        // POST: HLV_CLB/Create
        [HttpPost]
        public ActionResult Create(HLV_CLB hLV_CLB)
        {
            try
            {
                QLTong<HLV_CLB> t = new QLHLV_CLB();
                t.them(hLV_CLB);
                t.getdata();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HLV_CLB/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            QLTong<HLV_CLB> t = new QLHLV_CLB();

            if (!t.istimkiem(id))
            {
                return HttpNotFound();
            }

            ViewBag.MACLB = t.getListSelect("CAULACBO", "TENCLB");
            ViewBag.MAHLV = t.getListSelect("HLV", "TENHLV");
            return View(t.xemChiTiet(id));
        }

        // POST: HLV_CLB/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, HLV_CLB hLV_CLB)
        {
            QLTong<HLV_CLB> t = new QLHLV_CLB();
            t.sua(id, hLV_CLB);
            t.getdata();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(string id, HLV_CLB hLV_CLB)
        {
            QLTong<HLV_CLB> t = new QLHLV_CLB();
            t.xoa(id);
            t.getdata();
            return View("Index", t.DS);
        }
    }
}

XML/XML/Views/HLV_CLB/Create.cshtml
@model XML.Models.HLV_CLB
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<main id="main" class="main">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>HLV_CLB</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MAHLV,"Huấn Luyện Viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownList("MAHLV", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MAHLV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MACLB,"Câu lạc bộ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownList("MACLB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MACLB, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VAITRO,"Vai trò", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VAITRO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VAITRO, "", new { @class = "text-danger" })
                </div>
            </div>

           

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/HLV_CLB/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Delete</h2>

XML/XML/Views/HLV_CLB/Details.cshtml
@model XML.Models.HLV_CLB

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<main id="main" class="main">
    <h2>@ViewBag.Title</h2>
    <table border="1" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
        <tr>
            <td>
                <table cellpadding="2" cellspacing="10">
                    <tr>
                        <td>Mã Huấn Luyện Viên:</td>
                        <td>@Html.DisplayFor(model => model.MAHLV)</td>
                    </tr>
                    <tr>
                        <td>Mã Câu lạc Bộ:</td>
                        <td>@Html.DisplayFor(model => model.MACLB)</td>
                    </tr>
                    <tr>
                        <td>vai trò:</td>
                        <td>@Html.DisplayFor(model => model.VAITRO)</td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

</main>

XML/XML/Views/HLV_CLB/Edit.cshtml
@model XML.Models.HLV_CLB
@{
    ViewBag.Title = "EDIT";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<main id="main" class="main">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>HLV_CLB</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MAHLV, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.DropDownList("MAHLV", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MAHLV, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MACLB, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.DropDownList("MACLB", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MACLB, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VAITRO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VAITRO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VAITRO, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="chỉnh sửa" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/HLV_CLB/Index.cshtml
@model IEnumerable<XML.Models.HLV_CLB>
@{
    ViewBag.Title = "Danh sách Huấn Luyện Viên_câu lạc bộ";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "MAHLV", rowsPerPage: 5);
}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Danh sách Huấn luyện viên_câu lạc bộ</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href=#>Home</a></li>
                <li class="breadcrumb-item">HLV_CLB</li>
                <li class="breadcrumb-item active">Dữ liệu</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">

                        @Html.ActionLink("Thêm", "Create", "HLV_CLB")

                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th>Họ Tên huấn Luyện Viên</th>
                                    <th>Tên Câu Lạc Bộ</th>
                                    <th>Vai Trò</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.MAHLV
                                        </td>
                                        <td>
                                            @item.MACLB
                                        </td>
                                        <td>
                                            @item.VAITRO
                                        </td>
                                        <td>
                                            @Html.ActionLink("Chi tiết", "Details", "HLV_CLB", new { id = item.MAHLV}, "") |
                                            @Html.ActionLink("Sửa", "Edit", "HLV_CLB", new { id = item.MAHLV}, "") |
                                            @Html.ActionLink("Xóa", "Delete", "HLV_CLB", new { id = item.MAHLV}, "")
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main>