XML/XML/Models/CauThu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace XML.Models
{
    public partial class CAUTHU
    {
        public string MACT { get; set; }
        public string HOTEN { get; set; }
        public string VITRI { get; set; }
        public string NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        public string SO { get; set; }
        public string MAQG { get; set; }
        public string MACLB { get; set; }
       
    }
}

XML/XML/Controllers/CauThuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using System.Xml.Linq;
using System.Xml.XPath;
using XML.Models;
using XML.QLData;

namespace XML.Controllers
{
    public class CauThuController : Controller
    {

        // GET: CauThu
        public ActionResult Index()
        {

            QLTong<CAUTHU> t = new QLCauThu();
            t.getdata();

            return View(t.DS);
        }

        // GET: CauThu/Details/5
        public ActionResult Details(string id)
        {

            QLTong<CAUTHU> t = new QLCauThu();

            if (!t.istimkiem(id))
            {
                return HttpNotFound();
            }

            return View(t.xemChiTiet(id));
        }
        // GET: CauThu/Create
        public ActionResult Create()
        {
            QLTong<CAUTHU> t = new QLCauThu();

            ViewBag.MACLB = t.getListSelect("CAULACBO", "TENCLB");

            ViewBag.MAQG = t.getListSelect("QUOCGIA", "TENQG");
            return View();
        }

        // POST: CauThu/Create
        [HttpPost]
        public ActionResult Create(CAUTHU cauthu)
        {

            try
            {
                QLTong<CAUTHU> t = new QLCauThu();
                t.them(cauthu);
                t.getdata();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CauThu/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            QLTong<CAUTHU> t = new QLCauThu();

            if (!t.istimkiem(id))
            {
                return HttpNotFound();
            }

            ViewBag.MACLB = t.getListSelect("CAULACBO", "TENCLB");
            ViewBag.MAQG = t.getListSelect("QUOCGIA", "TENQG");


            return View(t.xemChiTiet(id));
        }

        // POST: CauThu/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, CAUTHU cauthu)
        {
            QLTong<CAUTHU> t = new QLCauThu();
            t.sua(id, cauthu);
            t.getdata();
            return RedirectToAction("Index");
        }

        // POST: CauThu/Delete/5
        [HttpGet]
        public ActionResult Delete(string id)
        {
            QLTong<CAUTHU> t = new QLCauThu();
            t.xoa(id);
            t.getdata();
            return View("Index", t.DS);
            /* return RedirectToAction("Index");*/
        }
    }
}

XML/XML/Views/CauThu/Create.cshtml
@model XML.Models.CAUTHU
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<main id="main" class="main">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cầu thủ</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MACT, "Mã cầu thủ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MACT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MACT, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VITRI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VITRI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VITRI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HOTEN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HOTEN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HOTEN, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NGAYSINH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MACLB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownList("MACLB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MACLB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MAQG, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MAQG", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MAQG, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/CauThu/Details.cshtml
@model XML.Models.CAUTHU

@{
    ViewBag.Title = "Thông tin cầu thủ";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<main id="main" class="main">
    <h2>@ViewBag.Title</h2>
    <table border="1" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
        <tr>
            <td>
                <table cellpadding="2" cellspacing="10">
                    <tr>
                        <td>Họ tên cầu thủ:</td>
                        <td>@Html.DisplayFor(model => model.HOTEN)</td>
                    </tr>
                    <tr>
                        <td>Vị trí:</td>
                        <td>@Html.DisplayFor(model => model.VITRI)</td>
                    </tr>
                    <tr>
                        <td>Ngày sinh:</td>
                        <td>@Html.DisplayFor(model => model.NGAYSINH)</td>
                    </tr>
                    <tr>
                        <td>Câu lạc bộ:</td>
                        <td>@Html.DisplayFor(model => model.MACLB)</td>
                    </tr>
                    <tr>
                        <td>Số áo:</td>
                        <td>@Html.DisplayFor(model => model.SO)</td>
                    </tr>
                    <tr>
                        <td>Địa chỉ:</td>
                        <td>@Html.DisplayFor(model => model.DIACHI)</td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>

</main>

<p style="margin-left:50px;">
    @Html.ActionLink("Cập nhật", "Edit", new { id = Model.MACT }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

XML/XML/Views/CauThu/Edit.cshtml
@model XML.Models.CAUTHU
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


<main id="main" class="main">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Cầu thủ</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MACT, "Mã cầu thủ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MACT, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MACT, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.VITRI, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.VITRI, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.VITRI, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.HOTEN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.HOTEN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HOTEN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NGAYSINH, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NGAYSINH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NGAYSINH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DIACHI, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DIACHI, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DIACHI, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MACLB, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.DropDownList("MACLB", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MACLB, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MAQG, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("MAQG", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MAQG, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SO, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SO, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SO, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="SỬA" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/CauThu/Index.cshtml
@model IEnumerable<XML.Models.CAUTHU>
@{
    ViewBag.Title = "Danh sách cầu thủ";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenNV", rowsPerPage: 5);
}
<main id="main" class="main">

    <div class="pagetitle">
        <h1>Danh sách cầu thủ</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href=#>Home</a></li>
                <li class="breadcrumb-item">Sân</li>
                <li class="breadcrumb-item active">Dữ liệu</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">

                        @Html.ActionLink("Thêm", "Create", "CauThu")

                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th>Họ và tên</th>
                                    <th>Vị trí</th>
                                    <th>Tên câu lạc bộ</th>
                                    <th>Tên quốc gia</th>
                                    <th>Số áo</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.HOTEN
                                        </td>
                                        <td>
                                            @item.VITRI
                                        </td>
                                        <td>
                                            @item.MACLB
                                        </td>
                                        <td>
                                            @item.MAQG
                                        </td>
                                        <td>
                                            @item.SO
                                        </td>
                                        <td>
                                            @Html.ActionLink("Chi tiết", "Details", "CauThu", new { id = item.MACT }, "") |
                                            @Html.ActionLink("Sửa", "Edit", "CauThu", new { id = item.MACT }, "") |
                                            @Html.ActionLink("Xóa", "Delete", "CauThu", new { id = item.MACT }, "")
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main>