XML/XML/Models/TINH.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace XML.Models
{
    public partial class TINH
    {
        public string MATINH { get; set; }
        public string TENTINH { get; set; }

    }
}

XML/XML/Controllers/TinhController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XML.Models;
using XML.QLData;
using System.Runtime;
using System.Xml;
using System.Net;

namespace XML.Controllers
{
    public class TinhController : Controller
    {
        // GET: Tinh
        public ActionResult Index()
        {

            QLTong<TINH> qLTinh = new QLTinh();
            qLTinh.getdata();


            return View(qLTinh.DS);
        }

        // GET: San/Details/5
        public ActionResult Details(string id)
        {
            QLTong<TINH> t = new QLTinh();
            if (!t.istimkiem(id))
            {
                return HttpNotFound();
            }

            return View(t.xemChiTiet(id));
        }

        // GET: San/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: San/Create
        [HttpPost]
        public ActionResult Create(TINH tinhMoi)
        {

            try
            {
                QLTong<TINH> t = new QLTinh();
                t.them(tinhMoi);
                t.getdata();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }


        }

        // GET: San/Edit/5
        public ActionResult Edit(string id)
        {
            QLTong<TINH> t = new QLTinh();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (t.istimkiem(id))
            {
                return HttpNotFound();
            }

            return View(t.xemChiTiet(id));
        }

        // POST: San/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, TINH TinhSua)
        {


            ViewBag.t = "Thành công";
            QLTong<TINH> qLTinh = new QLTinh();
            qLTinh.sua(id, TinhSua);
            qLTinh.getdata();
            return View("Index", qLTinh.DS);
        }

        // GET: San/Delete/5

        [HttpGet]
        public ActionResult Delete(string id)
        {
            QLTong<TINH> qLTinh = new QLTinh();
            qLTinh.xoa(id);
            qLTinh.getdata();
            return View("Index", qLTinh.DS);
        }
    }
}

XML/XML/Views/Tinh/Create.cshtml
@model XML.Models.TINH
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}



<main id="main" class="main">
    @ViewBag.t

    <form action="/San/Create" method="post">
        Mã Tỉnh
        <input type="text" name="MATINH" />
        <br />
        Tên Tỉnh
        <input type="text" name="TENTINH" />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>

    </form>
    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/Tinh/Details.cshtml
@model XML.Models.TINH

@{
    ViewBag.Title = "Thông tin Tỉnh";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<main id="main" class="main">
    <h2>@ViewBag.Title</h2>
    <table border="1" cellpadding="0" cellspacing="0" style="font-size:14px;margin-left:50px;">
        <tr>
            <td>
                <table cellpadding="2" cellspacing="10">
                    <tr>
                        <td>Mã Tỉnh:</td>
                        <td>@Html.DisplayFor(model => model.MATINH)</td>
                    </tr>
                    <tr>
                        <td>Tên Tỉnh:</td>
                        <td>@Html.DisplayFor(model => model.TENTINH)</td>
                    </tr>

                </table>
            </td>
        </tr>
    </table>

</main>

<p style="margin-left:50px;">
    @Html.ActionLink("Cập nhật", "Edit", new { id = Model.MATINH }) |
    @Html.ActionLink("Quay lại", "Index")
</p>

XML/XML/Views/Tinh/Edit.cshtml
@model XML.Models.TINH
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


<main id="main" class="main">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Tỉnh</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MATINH, "Mã Tỉnh", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MATINH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MATINH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TENTINH,"Tên Tỉnh", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TENTINH, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TENTINH, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="chỉnh sửa" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/Tinh/Index.cshtml
@model IEnumerable<XML.Models.TINH>
@{
    ViewBag.Title = "Danh Sách Tỉnh";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TENTINH", rowsPerPage: 5);
}



<main id="main" class="main">

    <div class="pagetitle">
        <h1>Danh sách Tỉnh</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href=#>Home</a></li>
                <li class="breadcrumb-item">Tỉnh</li>
                <li class="breadcrumb-item active">Dữ liệu</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">

                        @Html.ActionLink("Thêm", "Create", "Tinh")
                        @ViewBag.t

                        <table class="table datatable">
                            <thead>
                                <tr>

                                    <th>Mã Tỉnh</th>
                                    <th>Tên Tỉnh</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.MATINH
                                        </td>
                                        <td>
                                            @item.TENTINH
                                        </td>
                                        <td>
                                            @Html.ActionLink("Sửa", "Edit", "Tinh", new { id = item.MATINH }, "") |
                                            @Html.ActionLink("Chi tiết", "Details", "Tinh", new { id = item.MATINH }, "") |
                                            @Html.ActionLink("Xóa", "Delete", "Tinh", new { id = item.MATINH }, "")
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->