XML/XML/Models/SAN.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace XML.Models
{
    public partial class SAN
    {
        public string MASAN { get; set; }
        public string TENSAN { get; set; }
        public string DIACHI { get; set; }
    }
}

XML/XML/Controllers/SanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using XML.Models;
using XML.QLData;
using System.Runtime;

namespace XML.Controllers
{
    public class SanController : Controller
    {

        public ActionResult Index()
        {

            QLTong<SAN> qLSan = new QLSan();
            qLSan.getdata();


            return View(qLSan.DS);
        }

        // GET: San/Details/5
        public ActionResult Details(string id)
        {
            QLTong<SAN> t = new QLSan();
            if (!t.istimkiem(id))
            {
                return HttpNotFound();
            }

            return View(t.xemChiTiet(id));
        }

        // GET: San/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: San/Create
        [HttpPost]
        public ActionResult Create(SAN sanMoi)
        {

            ViewBag.t = "thanh cong";
            QLTong<SAN> qLSan = new QLSan();
            qLSan.them(sanMoi);
            qLSan.getdata();

            return View("Index", qLSan.DS);


        }

        // GET: San/Edit/5
        public ActionResult Edit(string id)
        {
            QLTong<SAN> t = new QLSan();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (t.istimkiem(id))
            {
                return HttpNotFound();
            }

            return View(t.xemChiTiet(id));
        }

        // POST: San/Edit/5
        [HttpPost]
        public ActionResult Edit(string id, SAN sanSua)
        {


            QLTong<SAN> t = new QLSan();
            t.sua(id, sanSua);
            t.getdata();
            return RedirectToAction("Index");
        }

        // GET: San/Delete/5

        [HttpGet]
        public ActionResult Delete(string id)
        {
            QLTong<SAN> qLSan = new QLSan();
            qLSan.xoa(id);
            qLSan.getdata();
            return View("Index", qLSan.DS);
        }

    }
}

XML/XML/Views/San/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}



<main id="main" class="main">
    @ViewBag.t

    <form action="/San/Create" method="post">
        Mã Sân
        <input type="text" name="MASAN" />
        <br />
        Tên Sân
        <input type="text" name="TENSAN" />
        <br />
        Địa Chỉ
        <input type="text" name="DIACHI" />
        <br />
        <button type="submit"> gửi </button>

    </form>
    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/San/Edit.cshtml
@model XML.Models.SAN
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}


<main id="main" class="main">

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>SÂN VD</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.MASAN, "Mã Sân", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MASAN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MASAN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TENSAN, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TENSAN, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TENSAN, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="SỬA" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Quay lại", "Index")
    </div>
</main>

XML/XML/Views/San/Index.cshtml
@model IEnumerable<XML.Models.SAN>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}



<main id="main" class="main">

    <div class="pagetitle">
        <h1>Sân</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href=#>Home</a></li>
                <li class="breadcrumb-item">Sân</li>
                <li class="breadcrumb-item active">Dữ liệu</li>
            </ol>
        </nav>
    </div><!-- End Page Title -->

    <section class="section">
        <div class="row">
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-body">

                        @Html.ActionLink("Thêm", "Create", "San")
                        @ViewBag.t;

                        <table class="table datatable">
                            <thead>
                                <tr>

                                    <th>Mã Sân</th>
                                    <th>Tên Sân</th>
                                    <th>Địa Chỉ</th>
                                    <th>tinh nag</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.MASAN
                                        </td>
                                        <td>
                                            @item.TENSAN
                                        </td>
                                        <td>
                                            @item.DIACHI
                                        </td>
                                        <td>
                                            @Html.ActionLink("Sửa", "Edit", "San", new { id = item.MASAN }, "")
                                            @Html.ActionLink("Xóa", "Delete", "San", new { id = item.MASAN }, "")
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </section>

</main><!-- End #main -->